version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: kplus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RThFsRCXjQuJ
      POSTGRES_DB: kplus
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kplus-net

  api:
    build:
      context: ./kplus-backend
      dockerfile: Dockerfile
    container_name: kplus-api
    restart: unless-stopped
    env_file:
      - ./kplus-backend/.env
    environment:
      # se quiser sobrescrever variáveis localmente, use .env; mantive conexões ao db via service name
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - kplus-net

  web:
    build:
      context: ./kplus-web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://api:5000"
        REACT_APP_API_URL: "http://api:5000"
    container_name: kplus-web
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - kplus-net

volumes:
  pgdata:

networks:
  kplus-net:
    driver: bridge